name: screen_protection
description: A Flutter plugin that disables screenshots and screen recording on Android & iOS.
version: 0.0.1
homepage: https://github.com/AbdelmenamAdel/Screen_Protection
repository: https://github.com/AbdelmenamAdel/Screen_Protection
issue_tracker: https://github.com/AbdelmenamAdel/Screen_Protection/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.example.screen_protection
        pluginClass: ScreenProtectionPlugin
      ios:
        pluginClass: ScreenProtectionPlugin

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
